### ISSUE TITLE
Verifying tags "paused" failed

### ISSUE THREAD

**Issue by amazpyel** [askervin/fmbt-mplayertest#1]
**Run:**

```
~/fMBT-training/fmbt-mplayertest% fmbt smoke.conf
<fmbt_log>
<conf_load>
    <conf_file name="smoke.conf"/>
</conf_load>
<conf_execute>
    <action_name name="i%3Apause"/>
    <action_name name="i%3Acontinue"/>
    <action_name name="i%3Anext%20song"/>
    <action_name name="i%3Aprev%20song"/>
    <action_name name="i%3Anext%20song%20-%20already%20last"/>
    <action_name name="i%3Aprev%20song%20-%20already%20first"/>
    <action_name name="i%3Aadd%20song"/>
    <action_name name="i%3Areset%20playlist"/>
    <tag_name name="playing"/>
    <tag_name name="paused"/>
    <tag_name name="song%3D%3D1"/>
    <tag_name name="song%3D%3D2"/>
    <tag_name name="song%3D%3D3"/>
    <test_engine>
        <tags enabled="playing song%3D%3D1"/>
        <status steps="0" coverage="0.000000" scov="0.000000e+00"/>
        <current_time time="1422279068.414279"/>
        <suggested_action type="input" name="i%3Apause" time="1422279068.426585"/>
        <action type="input" name="i%3Apause" time="1422279069.478373"/>
        <adapter_executed>
        </adapter_executed>
        <tags enabled="paused song%3D%3D1"/>
        <remote msg="Assertion%20failure%20at%20adapter%28%29%20of%20tag%20%22paused%22%3A%20Player%20is%20not%20paused%0ATraceback%20%28most%20recent%20call%20last%29%3A%0A%20%20File%20%22mplayertest.aal%22%2C%20line%2094%2C%20in%20adapter%20of%20tag%20%22paused%22%0A%20%20%20%20adapter%20%7B%20assert%20playing%28%29%20%3D%3D%20False%2C%20%22Player%20is%20not%20paused%22%20%7D%0A"/>
Assertion failure at adapter() of tag "paused": Player is not paused
Traceback (most recent call last):
  File "mplayertest.aal", line 94, in adapter of tag "paused"
    adapter { assert playing() == False, "Player is not paused" }

        <status steps="1" coverage="0.125000" scov="1.250000e-01"/>
        <stop verdict="fail" reason="verifying%20tags%20%22paused%22%20failed."/>
        <current_time time="1422279069.487846"/>
        <elapsed_time time="1.087234"/>
    </test_engine>
</conf_execute>
fail: verifying tags "paused" failed.
</fmbt_log>

```

**aal.log:**

```
1422279067.397597 starting
1422279068.426753 mplayer command: pause
1422279069.478151 mplayer response: MPlayer svn r34540 (Ubuntu), built with gcc-4.6 (C) 2000-2012 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing 1.mp3.
libavformat version 53.21.1 (external)
Mismatching header version 53.19.0
Audio only file format detected.
Load subtitles in ./
==========================================================================
Requested audio codec family [mpg123] (afm=mpg123) not available.
Enable it at compilation.
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
libavcodec version 53.35.0 (external)
Mismatching header version 53.32.2
AUDIO: 22050 Hz, 2 ch, floatle, 48.0 kbit/3.40% (ratio: 6000->176400)
Selected audio codec: [ffmp3float] afm: ffmpeg (FFmpeg MPEG layer-3 audio)
==========================================================================
AO: [pulse] 22050Hz 2ch floatle (4 bytes per sample)
Video: no video
Starting playback...
pause

1422279069.486709 Exception <type 'exceptions.AssertionError'> in tag2adapter: Player is not paused
1422279069.487157 Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aalmodel.py", line 84, in call
    return eval(func.func_code, self._variables)
  File "mplayertest.aal", line 94, in adapter of tag "paused"
    adapter { assert playing() == False, "Player is not paused" }
AssertionError: Player is not paused

1422279069.487631 Assertion failure at adapter() of tag "paused": Player is not paused
Traceback (most recent call last):
  File "mplayertest.aal", line 94, in adapter of tag "paused"
    adapter { assert playing() == False, "Player is not paused" }

1422279069.487939 mplayer command: quit
1422279070.539243 mplayer response: quit

Exiting... (Quit)

1422279070.539693 quitting
```

**Test tab in fMBT editor:**

```
1   i:pause
2   i:continue
3   i:next song
4   i:prev song
5   i:prev song - already first
6   i:add song
7   i:reset playlist
8   i:next song - already last
pass    coverage 1.0 reached
```

**Environment**

```
MPlayer svn r34540 (Ubuntu), built with gcc-4.6 (C) 2000-2012 MPlayer Team
fMBT 0.18-1
Ubuntu 12.04.5 LTS 32 bits



```

**Comment by ciprian-cioba** [comment]
change in playing() function 
cmd = "pacmd list | grep RUNNING"
to
cmd = "pacmd list-sinks | grep RUNNING"

**Comment by askervin** [comment]
Thanks for your input!

However, I'd like to understand if this really fixes the issue.

`man pulse-cli-syntax` prints

```
STATUS COMMANDS
...
       list-sinks
              Show all currently registered sinks (resp. sources).
...
       info or ls or list
              A combination of all status commands described above (all three commands are synonyms).
```

so I suppose the result would stay the same. I'm not able to reproduce this issue.
